-- CreateTable
CREATE TABLE "FormResponse" (
    "id" SERIAL NOT NULL,
    "nomProjet" TEXT,
    "contactNom" TEXT,
    "contactFonction" TEXT,
    "email" TEXT,
    "telephone" TEXT,
    "siteWeb" TEXT,
    "dateMiseEnLigne" TIMESTAMP(3),
    "evenementAssocie" TEXT,
    "objectifs" TEXT[],
    "publicCible" TEXT,
    "pages" TEXT[],
    "contenuDisponible" TEXT,
    "pagesAMettreJour" BOOLEAN,
    "fonctionnalites" TEXT[],
    "venteEnLigne" BOOLEAN,
    "typesProduits" TEXT[],
    "nbProduits" TEXT,
    "besoinsSpecifiques" TEXT[],
    "responsive" BOOLEAN,
    "appAndroid" BOOLEAN,
    "appIos" BOOLEAN,
    "notifications" BOOLEAN,
    "logo" TEXT,
    "stylePrefere" TEXT,
    "gestionPlateforme" BOOLEAN,
    "hebergement" TEXT,
    "connexionOutils" BOOLEAN,
    "rgpd" BOOLEAN,
    "sauvegardes" BOOLEAN,
    "besoinsSupport" TEXT[],
    "budget" TEXT,
    "paiement" TEXT,
    "appelOffre" BOOLEAN,
    "communityManagement" TEXT[],
    "plateformes" TEXT[],
    "besoinsComm" TEXT[],
    "strategieExistante" TEXT,
    "referencement" TEXT[],
    "accompagnementSEO" TEXT[],
    "eReputation" BOOLEAN,
    "actionsAvis" TEXT[],
    "remarques" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "FormResponse_pkey" PRIMARY KEY ("id")
);
